### ISSUE TITLE
Investigate missing contributions

### ISSUE THREAD

**Issue by wenderjean** [Codeminer42/Punchclock#100]
I've recently noticed our bot is missing some contributions, every week, we should investigate what is going on.

In the past we used to receive "too many requests" from GitHub then It wouldn't surprise me if it is something related.
Recently I wiped out a couple of repositories that had never received contributions in order to test but it is not the issue :thinking: 

#### Source

- https://github.com/Codeminer42/Punchclock/tree/master/app/services/github

**Comment by geeksilva97** [comment]
Hey, @wenderjean. I would like to work on this. Can you assign me?

**Comment by geeksilva97** [comment]
Hi, guys. I examined the algorithm that imports contributions and it look great. The only thing that could be a problem is that the endpoint only returns 30 items by default. It would be a problem if our engineers' PRs were over 30.

Despite that, I'd like to propose an improvement at https://github.com/Codeminer42/Punchclock/blob/master/app/services/github/contributions/collect.rb#L13.

Our service traverses all repositories and each one traverses all engineers. It looks great but we're probably getting more results than needed. Fetching based on the repository might be bringing us PRs that aren't from our engineers.

Also, our algorithm is kinda subquadratic since in the worst case it traverses the `n` repositories and the `m` engineers, making our algorithm be `O(m*n)`, which is more than linear and less than quadratic.

What if we search based on engineer? In that scenario, we could get the pull requests only from our engineers and after filtering the repositories.

```
pull_requests = []
for each engineer of engineers
  pull_requests.append( load_engineers_pr_at (engineer, TODAY) ) # TODAY is a date in the format YYYY-MM-DD
  
for each pr of pull_requests
   if pr is not allowed # it could be a Set where we can check if it is a member
     pull_requests.remove(pr)
```
It would fetch only our engineers' PRs and instead of having a nested loop we would have separated ones. The efficiency would be `O(n+k)`, where `n` is the number of engineers and `k` is the number of gotten pull requests *.

\*_it is not considering the time for checking if an element is a Set member neither the how much storage is needed to keep the Set_

-----

We can search the Pull Requests of a specific user at a specific date using the following query on Github API https://api.github.com/search/issues?q=author:wenderjean+type:pr+created:2021-02-14,

I'm trying to perform such a query using `github_api`, but I'm not sure If it's possible. I've opened an ISSUE on the `github_api` repository asking for help. If it's not possible I think we can create our own service for searching pull requests, and when the searching feature comes out in `github_api` we can refactor this.

We could put it to run every day and search D-1 contributions. What do you think? @adbatista @wenderjean

**Comment by wenderjean** [comment]
Thanks for handling this issue @geeksilva97.

I recall when we started this initiative the API used to be kinda limited in terms of query options and it doesn't seem to have changed now. I spent some time reading through the [github_api source](https://github.com/piotrmurach/github/blob/master/lib/github_api/client/pull_requests.rb) and it seems we don't have an option to cap the results using a date range or even a user :'(

Anyway, I like the idea to search by user even though I'm aware we're not able to achieve a linear complexity due to the limitations of the API. I can imagine something like:

```
repositories = fetch_all_repositories_links
engineers = fetch_all_engineers_gh_username
pull_requests = []

for each engineer of engineers
  for each pr of pull_requests(engineer)
    if repositories.contains(pr.repository_url)
      pull_requests.append(pr)
```

I also performed some tests with the URL you sent and after some inconsistencies I ended up with this one that seems more accurate to me:

`client.search.issues(q: "author:wenderjean is:pr created:>2021-01-01")`

https://api.github.com/search/issues?q=author:wenderjean+is:pr+created:>2022-01-01

##### Important
_My concern is about the limits, I'd like to make sure we won't achieve limits by reaching API (e * repositories) times._

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
