### ISSUE TITLE
Upgrade NodeJs to ~> 18.10.x

### ISSUE THREAD

**Issue by adbatista** [Codeminer42/Punchclock#264]

**Comment by HeitorMC** [comment]
Hey, I've tried to update the nodeJS version to 18.10.0. However, I discovered that Node.JS 17 or above uses OpenSSL3, which is incompatible with the webpack version 4. The latest version of gem `webpacker` uses [webpack 4.x.x+](https://webpack.js.org/)

This is the error that I got when I tried to `app rails webpacker:compile`

```
node:internal/crypto/hash:71 this[_Handle] = new Hash(algorithm, xofLen); ^ Error: error:0308010C:digital envelope routines::unsupported
```

**Comment by HeitorMC** [comment]
Hey, I would like to be assign for this issue :handshake:

**Comment by HeitorMC** [comment]
Hey, I have some news: The gem `webpacker` has been retired, and for rails 7 apps, there are [three great default answers to JavaScript in 2021+](https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b), according to the README of [webpacker](https://github.com/rails/webpacker#readme). 

So, this gem won't receive new updates to include newer versions of JS and still will use [webpack 4.x.x+](https://webpack.js.org/). Also, there is a kind of "fork" of webpacker, called [Shakapacker](https://github.com/shakacode/shakapacker) but uses [Webpack v5+](https://webpack.js.org/). Both webpacker 4 and v5+ are incompatible with nodeJS > 17 because of the openSSL3.

Right now, I can picture two cases for this issue:

- Since we do have this issue #263, one approach would be to use importmap + hotwire instead of webpacker because this approach removes the node dependency in the project. However, I don't know viable is this choice.

- Stick with webpacker gem and use the node [flag](https://nodejs.org/es/blog/release/v17.0.0/) `--openssl-legacy-provider`.  This becomes a valid approach because nodeJS will be used only in build time, so it doesn't seem a problem, and solves the issue.

WDYT?

**Comment by adbatista** [comment]
I don't see a problem using node with openssl3, but since we will use hotwired let's go with this approach, thanks for investigating it

**Comment by abarbosa-godaddy** [comment]
should we add a hold tag to this issue? @adbatista

**Comment by adbatista** [comment]
why?
